# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scheduler_windows.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scheduler_windows.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17scheduler_windows.proto\x12\x11scheduler_windows\"\x07\n\x05\x45mpty\"H\n\x0cPrintRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x11\n\tis_duplex\x18\x03 \x01(\x08\"A\n\rPrintResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06job_id\x18\x03 \x01(\t\"\x1f\n\rStatusRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"Y\n\x0eStatusResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x13\n\x0btotal_pages\x18\x02 \x01(\x05\x12\x13\n\x0bsubmit_time\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\"B\n\x0fJobListResponse\x12/\n\x04jobs\x18\x01 \x03(\x0b\x32!.scheduler_windows.StatusResponse2\x86\x02\n\rPrinterBridge\x12T\n\x0f\x45xecutePrintJob\x12\x1f.scheduler_windows.PrintRequest\x1a .scheduler_windows.PrintResponse\x12S\n\x0cGetJobStatus\x12 .scheduler_windows.StatusRequest\x1a!.scheduler_windows.StatusResponse\x12J\n\nGetAllJobs\x12\x18.scheduler_windows.Empty\x1a\".scheduler_windows.JobListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scheduler_windows_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=46
  _globals['_EMPTY']._serialized_end=53
  _globals['_PRINTREQUEST']._serialized_start=55
  _globals['_PRINTREQUEST']._serialized_end=127
  _globals['_PRINTRESPONSE']._serialized_start=129
  _globals['_PRINTRESPONSE']._serialized_end=194
  _globals['_STATUSREQUEST']._serialized_start=196
  _globals['_STATUSREQUEST']._serialized_end=227
  _globals['_STATUSRESPONSE']._serialized_start=229
  _globals['_STATUSRESPONSE']._serialized_end=318
  _globals['_JOBLISTRESPONSE']._serialized_start=320
  _globals['_JOBLISTRESPONSE']._serialized_end=386
  _globals['_PRINTERBRIDGE']._serialized_start=389
  _globals['_PRINTERBRIDGE']._serialized_end=651
# @@protoc_insertion_point(module_scope)
