bind 0.0.0.0 -::1
protected-mode no
port 6379

requirepass __REDIS_PASSWORD__
masterauth __REDIS_PASSWORD__

replicaof 172.16.127.103 6379

replica-announce-ip 172.16.127.122
replica-announce-port 6379

appendonly yes
dir /data
