# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from .__python_out import print_pb2 as _dot_____python__out_dot_print__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in .__python_out/print_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PrinterBridgeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecutePrintJob = channel.unary_unary(
                '/print.PrinterBridge/ExecutePrintJob',
                request_serializer=_dot_____python__out_dot_print__pb2.PrintRequest.SerializeToString,
                response_deserializer=_dot_____python__out_dot_print__pb2.PrintResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/print.PrinterBridge/GetJobStatus',
                request_serializer=_dot_____python__out_dot_print__pb2.StatusRequest.SerializeToString,
                response_deserializer=_dot_____python__out_dot_print__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetAllJobs = channel.unary_unary(
                '/print.PrinterBridge/GetAllJobs',
                request_serializer=_dot_____python__out_dot_print__pb2.Empty.SerializeToString,
                response_deserializer=_dot_____python__out_dot_print__pb2.JobListResponse.FromString,
                _registered_method=True)


class PrinterBridgeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecutePrintJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """corresponding to get_printer_job_by_id()
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllJobs(self, request, context):
        """corresponding to get_printer_jobs()
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrinterBridgeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecutePrintJob': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePrintJob,
                    request_deserializer=_dot_____python__out_dot_print__pb2.PrintRequest.FromString,
                    response_serializer=_dot_____python__out_dot_print__pb2.PrintResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=_dot_____python__out_dot_print__pb2.StatusRequest.FromString,
                    response_serializer=_dot_____python__out_dot_print__pb2.StatusResponse.SerializeToString,
            ),
            'GetAllJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllJobs,
                    request_deserializer=_dot_____python__out_dot_print__pb2.Empty.FromString,
                    response_serializer=_dot_____python__out_dot_print__pb2.JobListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'print.PrinterBridge', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('print.PrinterBridge', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PrinterBridge(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecutePrintJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/print.PrinterBridge/ExecutePrintJob',
            _dot_____python__out_dot_print__pb2.PrintRequest.SerializeToString,
            _dot_____python__out_dot_print__pb2.PrintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/print.PrinterBridge/GetJobStatus',
            _dot_____python__out_dot_print__pb2.StatusRequest.SerializeToString,
            _dot_____python__out_dot_print__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/print.PrinterBridge/GetAllJobs',
            _dot_____python__out_dot_print__pb2.Empty.SerializeToString,
            _dot_____python__out_dot_print__pb2.JobListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
