scope: ${PATRONI_CLUSTER_NAME}
name: ${NODE_NAME}

restapi:
  listen: 0.0.0.0:8008
  connect_address: ${NODE_IP}:8008
  authentication:
    username: patroni
    password: ${PATRONI_RESTAPI_PASSWORD}

etcd:
  hosts: ${NODE1_IP}:2379,${NODE2_IP}:2379,${NODE3_IP}:2379

bootstrap:
  dcs:
    ttl: 20
    loop_wait: 5
    retry_timeout: 5
    maximum_lag_on_failover: 33554432  # 32MB
    synchronous_mode: false
    master_start_timeout: 0
    master_stop_timeout: 0
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        wal_level: replica
        hot_standby: "on"
        max_wal_senders: 10
        max_replication_slots: 10
        wal_keep_size: 256MB
        max_connections: 200
        shared_preload_libraries: ""

  post_init: /usr/local/bin/post_init.sh

  initdb:
    - encoding: UTF8
    - data-checksums

  pg_hba:
    - host replication ${PG_REPL_USER} 0.0.0.0/0 md5
    - host all all 0.0.0.0/0 md5

  users:
    ${PG_SUPERUSER}:
      password: ${PG_SUPERUSER_PASSWORD}
      options:
        - createrole
        - createdb
    ${PG_REPL_USER}:
      password: ${PG_REPL_PASSWORD}
      options:
        - replication

postgresql:
  listen: 0.0.0.0:5432
  connect_address: ${NODE_IP}:5432
  data_dir: /var/lib/postgresql/data/patroni
  pgpass: /tmp/pgpass0
  authentication:
    superuser:
      username: ${PG_SUPERUSER}
      password: ${PG_SUPERUSER_PASSWORD}
    replication:
      username: ${PG_REPL_USER}
      password: ${PG_REPL_PASSWORD}
  parameters:
    unix_socket_directories: '/var/run/postgresql'
  create_replica_methods:
    - basebackup
  basebackup:
    max-rate: '100M'
    checkpoint: 'fast'

watchdog:
  mode: off
