version: '3.8'

services:
  migration:
    build: .
    command: bash ./migrate-django.sh
    volumes:
      - .:/app
      - ./logs:/app/django-backend/logs
    environment:
      - DB_HOST=172.17.0.1
  web:
    build: .
    command: bash ./start.sh
    image: new_printing
    volumes:
      - .:/app
      - ./logs:/app/django-backend/logs
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=172.17.0.1
    depends_on:
      migration:
        condition: service_completed_successfully
