services:
  etcd:
    build: ./etcd
    image: pg-ha-etcd
    container_name: pg-ha-etcd
    volumes:
      - etcd-data:/etcd-data
    network_mode: host
    restart: unless-stopped
    environment:
      - NODE_NAME=${NODE_NAME}
      - NODE_IP=${NODE_IP}
      - ETCD_CLIENT_PORT=${ETCD_CLIENT_PORT}
      - ETCD_PEER_PORT=${ETCD_PEER_PORT}
      - ETCD_INITIAL_CLUSTER=${ETCD_INITIAL_CLUSTER}

  patroni:
    build:
      context: ./patroni
      args:
        PG_VERSION: ${PG_VERSION}
    image: pg-ha-patroni
    container_name: pg-ha-patroni
    network_mode: host
    restart: unless-stopped
    depends_on:
      etcd:
        condition: service_started
    environment:
      - PATRONI_CLUSTER_NAME=${PATRONI_CLUSTER_NAME}
      - NODE_NAME=${NODE_NAME}
      - NODE_IP=${NODE_IP}
      - NODE1_IP=${NODE1_IP}
      - NODE2_IP=${NODE2_IP}
      - NODE3_IP=${NODE3_IP}
      - PG_SUPERUSER=${PG_SUPERUSER}
      - PG_SUPERUSER_PASSWORD=${PG_SUPERUSER_PASSWORD}
      - PG_REPL_USER=${PG_REPL_USER}
      - PG_REPL_PASSWORD=${PG_REPL_PASSWORD}
      - PATRONI_RESTAPI_PASSWORD=${PATRONI_RESTAPI_PASSWORD}
    volumes:
      - pg-ha-data:/var/lib/postgresql/data

  haproxy:
    build: ./haproxy
    image: pg-ha-haproxy
    container_name: pg-ha-haproxy
    network_mode: host
    restart: unless-stopped
    depends_on:
      patroni:
        condition: service_started
    environment:
      - NODE1_IP=${NODE1_IP}
      - NODE2_IP=${NODE2_IP}
      - NODE3_IP=${NODE3_IP}

volumes:
  etcd-data:
  pg-ha-data:
